"""remove_chain_full_name_field

Revision ID: 0789141ace45
Revises: de10130405a2
Create Date: 2026-01-04 19:56:15.455301

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0789141ace45"
down_revision: str | Sequence[str] | None = "de10130405a2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chains", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chains", sa.Column("full_name", mysql.VARCHAR(length=200), nullable=False))
    # ### end Alembic commands ###
