"""add_merchant_settings_table

Revision ID: 07fb86469ded
Revises: c39638285be9
Create Date: 2026-01-10 22:29:15.420417

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "07fb86469ded"
down_revision: str | Sequence[str] | None = "c39638285be9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "merchant_settings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("deposit_expiry_seconds", sa.Integer(), nullable=False),
        sa.Column("callback_retry_count", sa.Integer(), nullable=False),
        sa.Column("telegram_bot_enabled", sa.Boolean(), nullable=False),
        sa.Column("telegram_chat_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("telegram_whitelist", sa.JSON(), nullable=False),
        sa.Column("telegram_notifications", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_merchant_settings_merchant_id"), "merchant_settings", ["merchant_id"], unique=True
    )
    op.alter_column(
        "orders",
        "requested_currency",
        existing_type=mysql.VARCHAR(length=20),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders",
        "requested_currency",
        existing_type=mysql.VARCHAR(length=20),
        server_default=sa.text("'USDT'"),
        existing_nullable=False,
    )
    op.drop_index(op.f("ix_merchant_settings_merchant_id"), table_name="merchant_settings")
    op.drop_table("merchant_settings")
    # ### end Alembic commands ###
