"""init

Revision ID: 7e2dc1b72a53
Revises:
Create Date: 2026-01-07 01:24:49.169870

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7e2dc1b72a53"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("remark", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("explorer_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("native_token", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("confirmation_blocks", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chains_code"), "chains", ["code"], unique=True)
    op.create_table(
        "fee_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("deposit_fee_percent", sa.DECIMAL(precision=10, scale=4), nullable=False),
        sa.Column("withdraw_fee_fixed", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("withdraw_fee_percent", sa.DECIMAL(precision=10, scale=4), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("remark", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=False),
        sa.Column("icon_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_stablecoin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tokens_code"), "tokens", ["code"], unique=True)
    op.create_table(
        "webhook_providers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column(
            "provider_type",
            sa.Enum(
                "tatum",
                "alchemy",
                "helius",
                "quicknode",
                "moralis",
                "getblock",
                "custom",
                name="webhookprovidertype",
            ),
            nullable=False,
        ),
        sa.Column("api_key", sa.Text(), nullable=True),
        sa.Column("api_secret", sa.Text(), nullable=True),
        sa.Column("webhook_secret", sa.Text(), nullable=True),
        sa.Column("webhook_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("webhook_id", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
        sa.Column("rpc_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("remark", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "token_chain_supports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("contract_address", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_native", sa.Boolean(), nullable=False),
        sa.Column("min_deposit", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("min_withdrawal", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("withdrawal_fee", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_chain_supports_chain_id"), "token_chain_supports", ["chain_id"], unique=False
    )
    op.create_index(
        op.f("ix_token_chain_supports_token_id"), "token_chain_supports", ["token_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clerk_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("SUPER_ADMIN", "MERCHANT", "SUPPORT", "GUEST", name="userrole"),
            nullable=False,
        ),
        sa.Column("google_secret", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("balance", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("credit_limit", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("deposit_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("withdraw_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
        sa.Column("fee_config_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["fee_config_id"],
            ["fee_configs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_clerk_id"), "users", ["clerk_id"], unique=True)
    op.create_index(op.f("ix_users_deposit_key"), "users", ["deposit_key"], unique=False)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_withdraw_key"), "users", ["withdraw_key"], unique=False)
    op.create_table(
        "webhook_provider_chains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("contract_addresses", sa.Text(), nullable=True),
        sa.Column("wallet_addresses", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["provider_id"],
            ["webhook_providers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_provider_chains_chain_id"),
        "webhook_provider_chains",
        ["chain_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_webhook_provider_chains_provider_id"),
        "webhook_provider_chains",
        ["provider_id"],
        unique=False,
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_no", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("out_trade_no", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("order_type", sa.Enum("DEPOSIT", "WITHDRAW", name="ordertype"), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("chain", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("fee", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("net_amount", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("wallet_address", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("to_address", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("tx_hash", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("confirmations", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMING",
                "PROCESSING",
                "SUCCESS",
                "FAILED",
                "EXPIRED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("callback_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
        sa.Column(
            "callback_status",
            sa.Enum("PENDING", "SUCCESS", "FAILED", name="callbackstatus"),
            nullable=False,
        ),
        sa.Column("callback_retry_count", sa.Integer(), nullable=False),
        sa.Column("last_callback_at", sa.DateTime(), nullable=True),
        sa.Column("extra_data", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True),
        sa.Column("remark", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("expire_time", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("merchant_id", "out_trade_no", name="uq_merchant_out_trade_no"),
    )
    op.create_index(op.f("ix_orders_chain"), "orders", ["chain"], unique=False)
    op.create_index(op.f("ix_orders_merchant_id"), "orders", ["merchant_id"], unique=False)
    op.create_index(op.f("ix_orders_order_no"), "orders", ["order_no"], unique=True)
    op.create_index(op.f("ix_orders_out_trade_no"), "orders", ["out_trade_no"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_token"), "orders", ["token"], unique=False)
    op.create_index(op.f("ix_orders_tx_hash"), "orders", ["tx_hash"], unique=False)
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "encrypted_private_key", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False
        ),
        sa.Column(
            "wallet_type",
            sa.Enum("RECHARGE", "HOT", "GAS", "COLD", name="wallettype"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("balance", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallets_address"), "wallets", ["address"], unique=True)
    op.create_index(op.f("ix_wallets_chain_id"), "wallets", ["chain_id"], unique=False)
    op.create_index(op.f("ix_wallets_token_id"), "wallets", ["token_id"], unique=False)
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=False)
    op.create_table(
        "balance_ledgers",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column(
            "change_type",
            sa.Enum(
                "ONLINE_RECHARGE",
                "MANUAL_RECHARGE",
                "MANUAL_DEDUCT",
                "FEE_FREEZE",
                "FEE_UNFREEZE",
                "FEE_SETTLE",
                "REFUND",
                "ADJUSTMENT",
                name="balancechangetype",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("pre_balance", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("post_balance", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("frozen_amount", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("pre_frozen", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("post_frozen", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("remark", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("operator_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_balance_ledgers_change_type"), "balance_ledgers", ["change_type"], unique=False
    )
    op.create_index(
        op.f("ix_balance_ledgers_created_at"), "balance_ledgers", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_balance_ledgers_operator_id"), "balance_ledgers", ["operator_id"], unique=False
    )
    op.create_index(
        op.f("ix_balance_ledgers_order_id"), "balance_ledgers", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_balance_ledgers_user_id"), "balance_ledgers", ["user_id"], unique=False
    )
    op.create_table(
        "payment_channels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column(
            "status", sa.Enum("ACTIVE", "PAUSED", "DISABLED", name="channelstatus"), nullable=False
        ),
        sa.Column("min_amount", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("max_amount", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("daily_limit", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("balance_limit", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("daily_used", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("last_reset_date", sa.DateTime(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_payment_channels_chain_id"), "payment_channels", ["chain_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_channels_token_id"), "payment_channels", ["token_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_channels_user_id"), "payment_channels", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_payment_channels_wallet_id"), "payment_channels", ["wallet_id"], unique=False
    )
    op.create_table(
        "recharge_addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("AVAILABLE", "ASSIGNED", "LOCKED", "DISABLED", name="rechargeaddressstatus"),
            nullable=False,
        ),
        sa.Column("total_recharged", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("last_recharge_at", sa.DateTime(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recharge_addresses_chain_id"), "recharge_addresses", ["chain_id"], unique=False
    )
    op.create_index(
        op.f("ix_recharge_addresses_status"), "recharge_addresses", ["status"], unique=False
    )
    op.create_index(
        "ix_recharge_addresses_status_chain",
        "recharge_addresses",
        ["status", "chain_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recharge_addresses_token_id"), "recharge_addresses", ["token_id"], unique=False
    )
    op.create_index(
        "ix_recharge_addresses_user_chain_token",
        "recharge_addresses",
        ["user_id", "chain_id", "token_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recharge_addresses_user_id"), "recharge_addresses", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_recharge_addresses_wallet_id"), "recharge_addresses", ["wallet_id"], unique=True
    )
    op.create_table(
        "collect_tasks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("recharge_address_id", sa.Integer(), nullable=False),
        sa.Column("hot_wallet_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "PROCESSING", "SUCCESS", "FAILED", "SKIPPED", name="collecttaskstatus"
            ),
            nullable=False,
        ),
        sa.Column("tx_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("gas_used", sa.DECIMAL(precision=32, scale=8), nullable=True),
        sa.Column("gas_price", sa.DECIMAL(precision=32, scale=8), nullable=True),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("max_retries", sa.Integer(), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(), nullable=True),
        sa.Column("executed_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["hot_wallet_id"],
            ["wallets.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recharge_address_id"],
            ["recharge_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_collect_tasks_chain_id"), "collect_tasks", ["chain_id"], unique=False)
    op.create_index(
        op.f("ix_collect_tasks_created_at"), "collect_tasks", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_collect_tasks_hot_wallet_id"), "collect_tasks", ["hot_wallet_id"], unique=False
    )
    op.create_index(
        op.f("ix_collect_tasks_recharge_address_id"),
        "collect_tasks",
        ["recharge_address_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collect_tasks_scheduled_at"), "collect_tasks", ["scheduled_at"], unique=False
    )
    op.create_index(op.f("ix_collect_tasks_status"), "collect_tasks", ["status"], unique=False)
    op.create_index(
        "ix_collect_tasks_status_scheduled",
        "collect_tasks",
        ["status", "scheduled_at"],
        unique=False,
    )
    op.create_index(op.f("ix_collect_tasks_token_id"), "collect_tasks", ["token_id"], unique=False)
    op.create_index(op.f("ix_collect_tasks_tx_hash"), "collect_tasks", ["tx_hash"], unique=False)
    op.create_table(
        "recharge_orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_no", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("recharge_address_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("expected_amount", sa.DECIMAL(precision=32, scale=8), nullable=False),
        sa.Column("actual_amount", sa.DECIMAL(precision=32, scale=8), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "DETECTED",
                "CONFIRMING",
                "SUCCESS",
                "EXPIRED",
                "FAILED",
                name="rechargeorderstatus",
            ),
            nullable=False,
        ),
        sa.Column("tx_hash", sqlmodel.sql.sqltypes.AutoString(length=128), nullable=True),
        sa.Column("confirmations", sa.Integer(), nullable=False),
        sa.Column("required_confirmations", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(), nullable=True),
        sa.Column("credited_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recharge_address_id"],
            ["recharge_addresses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recharge_orders_chain_id"), "recharge_orders", ["chain_id"], unique=False
    )
    op.create_index(
        op.f("ix_recharge_orders_created_at"), "recharge_orders", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_recharge_orders_expires_at"), "recharge_orders", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_recharge_orders_order_no"), "recharge_orders", ["order_no"], unique=True
    )
    op.create_index(
        op.f("ix_recharge_orders_recharge_address_id"),
        "recharge_orders",
        ["recharge_address_id"],
        unique=False,
    )
    op.create_index(op.f("ix_recharge_orders_status"), "recharge_orders", ["status"], unique=False)
    op.create_index(
        "ix_recharge_orders_status_expires",
        "recharge_orders",
        ["status", "expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recharge_orders_token_id"), "recharge_orders", ["token_id"], unique=False
    )
    op.create_index(
        op.f("ix_recharge_orders_tx_hash"), "recharge_orders", ["tx_hash"], unique=False
    )
    op.create_index(
        op.f("ix_recharge_orders_user_id"), "recharge_orders", ["user_id"], unique=False
    )
    op.create_index(
        "ix_recharge_orders_user_status", "recharge_orders", ["user_id", "status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_recharge_orders_user_status", table_name="recharge_orders")
    op.drop_index(op.f("ix_recharge_orders_user_id"), table_name="recharge_orders")
    op.drop_index(op.f("ix_recharge_orders_tx_hash"), table_name="recharge_orders")
    op.drop_index(op.f("ix_recharge_orders_token_id"), table_name="recharge_orders")
    op.drop_index("ix_recharge_orders_status_expires", table_name="recharge_orders")
    op.drop_index(op.f("ix_recharge_orders_status"), table_name="recharge_orders")
    op.drop_index(op.f("ix_recharge_orders_recharge_address_id"), table_name="recharge_orders")
    op.drop_index(op.f("ix_recharge_orders_order_no"), table_name="recharge_orders")
    op.drop_index(op.f("ix_recharge_orders_expires_at"), table_name="recharge_orders")
    op.drop_index(op.f("ix_recharge_orders_created_at"), table_name="recharge_orders")
    op.drop_index(op.f("ix_recharge_orders_chain_id"), table_name="recharge_orders")
    op.drop_table("recharge_orders")
    op.drop_index(op.f("ix_collect_tasks_tx_hash"), table_name="collect_tasks")
    op.drop_index(op.f("ix_collect_tasks_token_id"), table_name="collect_tasks")
    op.drop_index("ix_collect_tasks_status_scheduled", table_name="collect_tasks")
    op.drop_index(op.f("ix_collect_tasks_status"), table_name="collect_tasks")
    op.drop_index(op.f("ix_collect_tasks_scheduled_at"), table_name="collect_tasks")
    op.drop_index(op.f("ix_collect_tasks_recharge_address_id"), table_name="collect_tasks")
    op.drop_index(op.f("ix_collect_tasks_hot_wallet_id"), table_name="collect_tasks")
    op.drop_index(op.f("ix_collect_tasks_created_at"), table_name="collect_tasks")
    op.drop_index(op.f("ix_collect_tasks_chain_id"), table_name="collect_tasks")
    op.drop_table("collect_tasks")
    op.drop_index(op.f("ix_recharge_addresses_wallet_id"), table_name="recharge_addresses")
    op.drop_index(op.f("ix_recharge_addresses_user_id"), table_name="recharge_addresses")
    op.drop_index("ix_recharge_addresses_user_chain_token", table_name="recharge_addresses")
    op.drop_index(op.f("ix_recharge_addresses_token_id"), table_name="recharge_addresses")
    op.drop_index("ix_recharge_addresses_status_chain", table_name="recharge_addresses")
    op.drop_index(op.f("ix_recharge_addresses_status"), table_name="recharge_addresses")
    op.drop_index(op.f("ix_recharge_addresses_chain_id"), table_name="recharge_addresses")
    op.drop_table("recharge_addresses")
    op.drop_index(op.f("ix_payment_channels_wallet_id"), table_name="payment_channels")
    op.drop_index(op.f("ix_payment_channels_user_id"), table_name="payment_channels")
    op.drop_index(op.f("ix_payment_channels_token_id"), table_name="payment_channels")
    op.drop_index(op.f("ix_payment_channels_chain_id"), table_name="payment_channels")
    op.drop_table("payment_channels")
    op.drop_index(op.f("ix_balance_ledgers_user_id"), table_name="balance_ledgers")
    op.drop_index(op.f("ix_balance_ledgers_order_id"), table_name="balance_ledgers")
    op.drop_index(op.f("ix_balance_ledgers_operator_id"), table_name="balance_ledgers")
    op.drop_index(op.f("ix_balance_ledgers_created_at"), table_name="balance_ledgers")
    op.drop_index(op.f("ix_balance_ledgers_change_type"), table_name="balance_ledgers")
    op.drop_table("balance_ledgers")
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_token_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_chain_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_address"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_orders_tx_hash"), table_name="orders")
    op.drop_index(op.f("ix_orders_token"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_out_trade_no"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_no"), table_name="orders")
    op.drop_index(op.f("ix_orders_merchant_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_chain"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(
        op.f("ix_webhook_provider_chains_provider_id"), table_name="webhook_provider_chains"
    )
    op.drop_index(op.f("ix_webhook_provider_chains_chain_id"), table_name="webhook_provider_chains")
    op.drop_table("webhook_provider_chains")
    op.drop_index(op.f("ix_users_withdraw_key"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_deposit_key"), table_name="users")
    op.drop_index(op.f("ix_users_clerk_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_token_chain_supports_token_id"), table_name="token_chain_supports")
    op.drop_index(op.f("ix_token_chain_supports_chain_id"), table_name="token_chain_supports")
    op.drop_table("token_chain_supports")
    op.drop_table("webhook_providers")
    op.drop_index(op.f("ix_tokens_code"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_table("fee_configs")
    op.drop_index(op.f("ix_chains_code"), table_name="chains")
    op.drop_table("chains")
    # ### end Alembic commands ###
