"""add_requested_amount_to_orders

Revision ID: 9c846f57b69b
Revises: b8da3360706c
Create Date: 2026-01-08 23:32:58.936527

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c846f57b69b"
down_revision: str | Sequence[str] | None = "b8da3360706c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "orders", sa.Column("requested_amount", sa.DECIMAL(precision=32, scale=8), nullable=False)
    )
    op.alter_column(
        "users",
        "frozen_balance",
        existing_type=mysql.DECIMAL(precision=32, scale=8),
        server_default=None,
        existing_nullable=False,
    )
    op.drop_constraint(op.f("fk_users_parent_id"), "users", type_="foreignkey")
    op.create_foreign_key(None, "users", "users", ["parent_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.create_foreign_key(
        op.f("fk_users_parent_id"), "users", "users", ["parent_id"], ["id"], ondelete="SET NULL"
    )
    op.alter_column(
        "users",
        "frozen_balance",
        existing_type=mysql.DECIMAL(precision=32, scale=8),
        server_default=sa.text("'0.00000000'"),
        existing_nullable=False,
    )
    op.drop_column("orders", "requested_amount")
    # ### end Alembic commands ###
