"""initial_schema

Revision ID: 9fcfe5fa8962
Revises:
Create Date: 2026-01-02 21:50:13.281499

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fcfe5fa8962"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fee_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("chain", sa.Enum("TRON", "ETHEREUM", "SOLANA", name="chain"), nullable=False),
        sa.Column("fee_percentage", sa.Numeric(precision=10, scale=6), nullable=False),
        sa.Column("fixed_fee", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("min_withdrawal", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("max_withdrawal", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("min_deposit", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_fee_configs_chain"), "fee_configs", ["chain"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clerk_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("SUPER_ADMIN", "MERCHANT", "SUPPORT", "GUEST", name="userrole"),
            nullable=False,
        ),
        sa.Column("google_secret", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_clerk_id"), "users", ["clerk_id"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_table(
        "merchants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("merchant_no", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("deposit_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("withdraw_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column(
            "callback_ip_whitelist", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_merchants_merchant_no"), "merchants", ["merchant_no"], unique=True)
    op.create_index(op.f("ix_merchants_user_id"), "merchants", ["user_id"], unique=True)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_no", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("merchant_ref", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_type", sa.Enum("DEPOSIT", "WITHDRAWAL", name="ordertype"), nullable=False),
        sa.Column("chain", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("token", sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("fee", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("net_amount", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMING",
                "PROCESSING",
                "SUCCESS",
                "FAILED",
                "EXPIRED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.Column("wallet_address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("tx_hash", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("confirmations", sa.Integer(), nullable=False),
        sa.Column("chain_metadata", mysql.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_chain"), "orders", ["chain"], unique=False)
    op.create_index(op.f("ix_orders_created_at"), "orders", ["created_at"], unique=False)
    op.create_index(op.f("ix_orders_merchant_ref"), "orders", ["merchant_ref"], unique=False)
    op.create_index(op.f("ix_orders_order_no"), "orders", ["order_no"], unique=True)
    op.create_index(op.f("ix_orders_order_type"), "orders", ["order_type"], unique=False)
    op.create_index(op.f("ix_orders_status"), "orders", ["status"], unique=False)
    op.create_index(op.f("ix_orders_token"), "orders", ["token"], unique=False)
    op.create_index(op.f("ix_orders_tx_hash"), "orders", ["tx_hash"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("chain", sa.Enum("TRON", "ETHEREUM", "SOLANA", name="chain"), nullable=False),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "encrypted_private_key", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False
        ),
        sa.Column(
            "wallet_type", sa.Enum("DEPOSIT", "GAS", "COLD", name="wallettype"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallets_address"), "wallets", ["address"], unique=False)
    op.create_index(op.f("ix_wallets_chain"), "wallets", ["chain"], unique=False)
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=False)
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("wallet_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column(
            "tx_type",
            sa.Enum("DEPOSIT", "WITHDRAWAL", "FEE", "SWEEP", "ADJUSTMENT", name="transactiontype"),
            nullable=False,
        ),
        sa.Column(
            "direction", sa.Enum("CREDIT", "DEBIT", name="transactiondirection"), nullable=False
        ),
        sa.Column("amount", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("pre_balance", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("post_balance", sa.Numeric(precision=32, scale=8), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["wallet_id"],
            ["wallets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_created_at"), "transactions", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_transactions_order_id"), "transactions", ["order_id"], unique=False)
    op.create_index(op.f("ix_transactions_tx_type"), "transactions", ["tx_type"], unique=False)
    op.create_index(op.f("ix_transactions_user_id"), "transactions", ["user_id"], unique=False)
    op.create_index(op.f("ix_transactions_wallet_id"), "transactions", ["wallet_id"], unique=False)
    op.create_table(
        "webhook_deliveries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("event_type", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("event_id", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
        sa.Column("url", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
        sa.Column("payload", mysql.JSON(), nullable=True),
        sa.Column("response_status", sa.Integer(), nullable=True),
        sa.Column("response_body", sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_attempt_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_webhook_deliveries_created_at"), "webhook_deliveries", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_event_id"), "webhook_deliveries", ["event_id"], unique=True
    )
    op.create_index(
        op.f("ix_webhook_deliveries_event_type"), "webhook_deliveries", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_order_id"), "webhook_deliveries", ["order_id"], unique=False
    )
    op.create_index(
        op.f("ix_webhook_deliveries_success"), "webhook_deliveries", ["success"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_webhook_deliveries_success"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_order_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_event_type"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_event_id"), table_name="webhook_deliveries")
    op.drop_index(op.f("ix_webhook_deliveries_created_at"), table_name="webhook_deliveries")
    op.drop_table("webhook_deliveries")
    op.drop_index(op.f("ix_transactions_wallet_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_user_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_tx_type"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_order_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_created_at"), table_name="transactions")
    op.drop_table("transactions")
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_chain"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_address"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_tx_hash"), table_name="orders")
    op.drop_index(op.f("ix_orders_token"), table_name="orders")
    op.drop_index(op.f("ix_orders_status"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_type"), table_name="orders")
    op.drop_index(op.f("ix_orders_order_no"), table_name="orders")
    op.drop_index(op.f("ix_orders_merchant_ref"), table_name="orders")
    op.drop_index(op.f("ix_orders_created_at"), table_name="orders")
    op.drop_index(op.f("ix_orders_chain"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_merchants_user_id"), table_name="merchants")
    op.drop_index(op.f("ix_merchants_merchant_no"), table_name="merchants")
    op.drop_table("merchants")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_clerk_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_fee_configs_chain"), table_name="fee_configs")
    op.drop_table("fee_configs")
    # ### end Alembic commands ###
