"""add_rpc_url_to_webhook_providers

Revision ID: a096f7e01975
Revises: 9e82cc1731b6
Create Date: 2026-01-05 19:53:19.276229

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a096f7e01975"
down_revision: str | Sequence[str] | None = "9e82cc1731b6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "webhook_providers",
        sa.Column("rpc_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("webhook_providers", "rpc_url")
    # ### end Alembic commands ###
