"""add_exchange_rate_tables_and_order_fields

Revision ID: c39638285be9
Revises: 9c846f57b69b
Create Date: 2026-01-10 00:31:16.279209

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c39638285be9"
down_revision: str | Sequence[str] | None = "9c846f57b69b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchange_rate_sources",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("base_currency", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("quote_currency", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("source_name", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("source_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("response_path", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
        sa.Column("sync_interval", sa.Integer(), nullable=False),
        sa.Column("current_rate", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("last_synced_at", sa.DateTime(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("base_currency", "quote_currency", name="uq_source_currency_pair"),
    )
    op.create_index(
        op.f("ix_exchange_rate_sources_base_currency"),
        "exchange_rate_sources",
        ["base_currency"],
        unique=False,
    )
    op.create_index(
        op.f("ix_exchange_rate_sources_quote_currency"),
        "exchange_rate_sources",
        ["quote_currency"],
        unique=False,
    )
    op.create_table(
        "exchange_rates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("base_currency", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("quote_currency", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column(
            "mode",
            sa.Enum("SYSTEM", "ADJUSTMENT", "CUSTOM", name="exchangeratemode"),
            nullable=False,
        ),
        sa.Column("rate", sa.DECIMAL(precision=20, scale=8), nullable=True),
        sa.Column("adjustment", sa.DECIMAL(precision=10, scale=6), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "base_currency", "quote_currency", name="uq_merchant_currency_pair"
        ),
    )
    op.create_index(
        op.f("ix_exchange_rates_base_currency"), "exchange_rates", ["base_currency"], unique=False
    )
    op.create_index(
        op.f("ix_exchange_rates_quote_currency"), "exchange_rates", ["quote_currency"], unique=False
    )
    op.create_index(op.f("ix_exchange_rates_user_id"), "exchange_rates", ["user_id"], unique=False)
    op.add_column(
        "orders",
        sa.Column(
            "requested_currency",
            sqlmodel.sql.sqltypes.AutoString(length=20),
            nullable=False,
            server_default="USDT",
        ),
    )
    op.add_column(
        "orders", sa.Column("exchange_rate", sa.DECIMAL(precision=20, scale=8), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("orders", "exchange_rate")
    op.drop_column("orders", "requested_currency")
    op.drop_index(op.f("ix_exchange_rates_user_id"), table_name="exchange_rates")
    op.drop_index(op.f("ix_exchange_rates_quote_currency"), table_name="exchange_rates")
    op.drop_index(op.f("ix_exchange_rates_base_currency"), table_name="exchange_rates")
    op.drop_table("exchange_rates")
    op.drop_index(
        op.f("ix_exchange_rate_sources_quote_currency"), table_name="exchange_rate_sources"
    )
    op.drop_index(
        op.f("ix_exchange_rate_sources_base_currency"), table_name="exchange_rate_sources"
    )
    op.drop_table("exchange_rate_sources")
    # ### end Alembic commands ###
