"""add_merchant_fields_and_fee_config

Revision ID: ccc97a9bfe00
Revises: 0789141ace45
Create Date: 2026-01-04 21:19:26.102810

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ccc97a9bfe00"
down_revision: str | Sequence[str] | None = "0789141ace45"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("balance", sa.DECIMAL(precision=32, scale=8), nullable=False))
    op.add_column(
        "users", sa.Column("credit_limit", sa.DECIMAL(precision=32, scale=8), nullable=False)
    )
    op.add_column(
        "users",
        sa.Column("deposit_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    )
    op.add_column(
        "users",
        sa.Column("withdraw_key", sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    )
    op.add_column("users", sa.Column("fee_config_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_users_deposit_key"), "users", ["deposit_key"], unique=False)
    op.create_index(op.f("ix_users_withdraw_key"), "users", ["withdraw_key"], unique=False)
    op.create_foreign_key(None, "users", "fee_configs", ["fee_config_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="foreignkey")
    op.drop_index(op.f("ix_users_withdraw_key"), table_name="users")
    op.drop_index(op.f("ix_users_deposit_key"), table_name="users")
    op.drop_column("users", "fee_config_id")
    op.drop_column("users", "withdraw_key")
    op.drop_column("users", "deposit_key")
    op.drop_column("users", "credit_limit")
    op.drop_column("users", "balance")
    # ### end Alembic commands ###
