"""initial schema with user, wallet, chain, token models

Revision ID: de10130405a2
Revises:
Create Date: 2026-01-03 21:07:43.137921

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "de10130405a2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chains",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("remark", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("rpc_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("explorer_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("native_token", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
        sa.Column("confirmation_blocks", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chains_code"), "chains", ["code"], unique=True)
    op.create_table(
        "tokens",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("full_name", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("remark", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=False),
        sa.Column("icon_url", sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
        sa.Column("is_stablecoin", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tokens_code"), "tokens", ["code"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("clerk_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "role",
            sa.Enum("SUPER_ADMIN", "MERCHANT", "SUPPORT", "GUEST", name="userrole"),
            nullable=False,
        ),
        sa.Column("google_secret", sqlmodel.sql.sqltypes.AutoString(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_clerk_id"), "users", ["clerk_id"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_table(
        "token_chain_supports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=False),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("contract_address", sqlmodel.sql.sqltypes.AutoString(length=200), nullable=False),
        sa.Column("decimals", sa.Integer(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("is_native", sa.Boolean(), nullable=False),
        sa.Column("min_deposit", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("min_withdrawal", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("withdrawal_fee", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_token_chain_supports_chain_id"), "token_chain_supports", ["chain_id"], unique=False
    )
    op.create_index(
        op.f("ix_token_chain_supports_token_id"), "token_chain_supports", ["token_id"], unique=False
    )
    op.create_table(
        "wallets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("chain_id", sa.Integer(), nullable=False),
        sa.Column("token_id", sa.Integer(), nullable=True),
        sa.Column("address", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
        sa.Column(
            "encrypted_private_key", sqlmodel.sql.sqltypes.AutoString(length=1024), nullable=False
        ),
        sa.Column(
            "wallet_type", sa.Enum("DEPOSIT", "GAS", "COLD", name="wallettype"), nullable=False
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("label", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
        sa.Column("balance", sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chain_id"],
            ["chains.id"],
        ),
        sa.ForeignKeyConstraint(
            ["token_id"],
            ["tokens.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wallets_address"), "wallets", ["address"], unique=True)
    op.create_index(op.f("ix_wallets_chain_id"), "wallets", ["chain_id"], unique=False)
    op.create_index(op.f("ix_wallets_token_id"), "wallets", ["token_id"], unique=False)
    op.create_index(op.f("ix_wallets_user_id"), "wallets", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wallets_user_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_token_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_chain_id"), table_name="wallets")
    op.drop_index(op.f("ix_wallets_address"), table_name="wallets")
    op.drop_table("wallets")
    op.drop_index(op.f("ix_token_chain_supports_token_id"), table_name="token_chain_supports")
    op.drop_index(op.f("ix_token_chain_supports_chain_id"), table_name="token_chain_supports")
    op.drop_table("token_chain_supports")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_clerk_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tokens_code"), table_name="tokens")
    op.drop_table("tokens")
    op.drop_index(op.f("ix_chains_code"), table_name="chains")
    op.drop_table("chains")
    # ### end Alembic commands ###
